const _ = {
    GROCERY_CATEGORY_ID:32,
    CAT_GROCERY_CATEGORY_ID:20,
    MEDICAL_CATEGORY_ID:52,
    COMPUTER_CATEGORY_ID: 22,
    PAGINATION_ITEM_LIMIT : 10,
    SHOP_PAGE_LIMIT : 25,
    SALT_ROUNDS:10,
}


module.exports = _